---
- name: Check Number of Sessions
  hosts: web
  vars:
    NUMBER_OF_SESSIONS: 4
  tasks:
  - name: Check Number of SESSIONS
    ansible.builtin.debug:
      msg: "Number of Sessions gt 5"
    when: NUMBER_OF_SESSIONS > 5
