---
- name: Gathering Facts
  hosts: web
  tasks:
  - name: Gathering Facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    when: os_family"=="RedHat"
