---
- name: Gathering Facts
  hosts: web
  become: true
  tasks:
  - name: Gathering Facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: Check if OS is Redhat or not
    ansible.builtin.debug:
      msg: "Yes it is RedHat"
    when: ansible_facts.os_family == "Redhat"

  - name: Check if OS is Debian or not
    ansible.builtin.debug:
      msg: "Yes it is Debain"
    when: ansible_facts.os_family == "Debian"
