---
- name: Install software packages
  hosts: web
  tasks:
  - name: checking command module
    ansible.builtin.command: cat /etc/passwd | grep root
    register: "{{ command_output }}"

  - name: Print Command output
    ansible.builtin.debug:
      msg: command_output

  - name: Checking Shell Module
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: "{{ shell_output }}"

  - name: Print Shell output
    ansible.builtin.debug:
      msg: shell_output
