---
- name: installing packages
  hosts: web
  become: true
  tasks:
  - name: Install package
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - telnet
    - zip
