---
- name: demo on filters
  hosts: local
  connection: local
  vars:
    Greeting: "Good Evening"
  tasks:
  - name: Greeting

    ansible.builtin.debug:
      msg: "Hi Mahesh, {{ Greeting | default('Good Morning') }}"
