---
- name: Get userid of Roboshop
  hosts: local
  connection: local
  tasks:
    - name: get id of Roboshop
      ansible.builtin.command: id roboshop 
      register: user_output 
      ignore_errors: true
    
    - name: user id output 
      ansible.builtin.debug:
        msg: "{{ user_output }}"
    
    - name: create user roboshop
      ansible.builtin.user:
        name: roboshop 
        create_home: yes 
      when: user_output.rc != 0